name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Common strategy to strip leading “v” off the tag
env:
  VERSION: ${{ github.ref_name }}

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cairosvg pillow
          pip install -r requirements.txt

      - name: Convert SVG to ICO
        run: |
          python -c "from cairosvg import svg2png; from PIL import Image; svg2png(url='icon.svg', write_to='icon.png'); Image.open('icon.png').save('icon.ico')"

      - name: Build executable
        run: |
          pyinstaller \
            --name="meet-zone-windows-${VERSION}" \
            --onefile --windowed \
            --icon=icon.ico \
            --add-data="roster.csv;." \
            --hidden-import=zoneinfo.tzpath \
            --hidden-import=pkg_resources.py2_warn \
            src/meet_zone/__main__.py

      - name: Generate SHA256 checksum
        run: |
          Get-FileHash -Algorithm SHA256 -Path "dist/meet-zone-windows-${VERSION}.exe" `
            | Select-Object -ExpandProperty Hash > "dist/meet-zone-windows-${VERSION}.exe.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meet-zone-windows-${{ env.VERSION }}
          path: |
            dist/meet-zone-windows-${{ env.VERSION }}.exe
            dist/meet-zone-windows-${{ env.VERSION }}.exe.sha256

  build-macos:
    runs-on: macos-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cairosvg pillow
          pip install -r requirements.txt
      - name: Convert SVG to PNG
        run: |
          python -c "from cairosvg import svg2png; svg2png(url='icon.svg', write_to='icon.png')"
      - name: Build executable
        run: |
          pyinstaller \
            --name="meet-zone-macos-${VERSION}" \
            --onefile --windowed \
            --icon=icon.png \
            --add-data="roster.csv:." \
            --hidden-import=zoneinfo.tzpath \
            --hidden-import=pkg_resources.py2_warn \
            src/meet_zone/__main__.py
      - name: Generate SHA256 checksum
        run: |
          shasum -a 256 "dist/meet-zone-macos-${VERSION}" > "dist/meet-zone-macos-${VERSION}.sha256"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meet-zone-macos-${{ env.VERSION }}
          path: |
            dist/meet-zone-macos-${{ env.VERSION }}
            dist/meet-zone-macos-${{ env.VERSION }}.sha256

  build-linux:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller cairosvg pillow
          pip install -r requirements.txt
      - name: Convert SVG to PNG
        run: |
          python -c "from cairosvg import svg2png; svg2png(url='icon.svg', write_to='icon.png')"
      - name: Build executable
        run: |
          pyinstaller \
            --name="meet-zone-linux-${VERSION}" \
            --onefile --windowed \
            --icon=icon.png \
            --add-data="roster.csv:." \
            --hidden-import=zoneinfo.tzpath \
            --hidden-import=pkg_resources.py2_warn \
            src/meet_zone/__main__.py
      - name: Generate SHA256 checksum
        run: |
          sha256sum "dist/meet-zone-linux-${VERSION}" > "dist/meet-zone-linux-${VERSION}.sha256"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: meet-zone-linux-${{ env.VERSION }}
          path: |
            dist/meet-zone-linux-${{ env.VERSION }}
            dist/meet-zone-linux-${{ env.VERSION }}.sha256

  create-source-archives:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Create ZIP archive
        run: |
          zip -r "meet-zone-source-${VERSION}.zip" . \
            -x "*.git*" "*__pycache__*" "*.pytest_cache*" "*.venv*" "*dist*" "*build*"
      - name: Create TAR.GZ archive
        run: |
          tar --exclude=".git" --exclude="__pycache__" --exclude=".pytest_cache" \
              --exclude=".venv" --exclude="dist" --exclude="build" \
            -czf "meet-zone-source-${VERSION}.tar.gz" .
      - name: Generate SHA256 checksums
        run: |
          sha256sum "meet-zone-source-${VERSION}.zip" > "meet-zone-source-${VERSION}.zip.sha256"
          sha256sum "meet-zone-source-${VERSION}.tar.gz" > "meet-zone-source-${VERSION}.tar.gz.sha256"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: source-code-${{ env.VERSION }}
          path: |
            meet-zone-source-${{ env.VERSION }}.zip
            meet-zone-source-${{ env.VERSION }}.zip.sha256
            meet-zone-source-${{ env.VERSION }}.tar.gz
            meet-zone-source-${{ env.VERSION }}.tar.gz.sha256

  create-release:
    needs:
      - build-windows
      - build-macos
      - build-linux
      - create-source-archives
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          # This becomes the release title
          name: "Build and Release ${{ env.VERSION }}"
          files: |
            dist/meet-zone-windows-${{ env.VERSION }}.exe
            dist/meet-zone-windows-${{ env.VERSION }}.exe.sha256
            dist/meet-zone-macos-${{ env.VERSION }}
            dist/meet-zone-macos-${{ env.VERSION }}.sha256
            dist/meet-zone-linux-${{ env.VERSION }}
            dist/meet-zone-linux-${{ env.VERSION }}.sha256
            meet-zone-source-${{ env.VERSION }}.zip
            meet-zone-source-${{ env.VERSION }}.zip.sha256
            meet-zone-source-${{ env.VERSION }}.tar.gz
            meet-zone-source-${{ env.VERSION }}.tar.gz.sha256
          draft: false
          prerelease: false
          generate_release_notes: true
